behaviors:
  Roll Over and Stand Up:
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 200
    summary_freq: 10000
    checkpoint_interval: 100000

    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 3
      vis_encode_type: simple

      memory:
        sequence_length: 32 # how long the sequences of experiences must be while training
        memory_size: 256  # the size of the memory the agent must keep

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

      #gail: 
      #  strength: 0.5
      #  demo_path: ../Demos/RollOverAndStand.demo

      #curiosity:
      #  strength: 0.02
      #  gamma: 0.99
      #  encoding_size: 256
      #  learning_rate: 3.0e-4

    #behavioral_cloning:
      #strength: 0.5
      #demo_path: ../Demos/RollOverAndStand.demo
      #steps: 5000
      #samples_per_update: 0
