behaviors:
  Roll Over and Stand Up:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      #gail: 
      #  strength: 0.5
      #  demo_path: ../Demos/RollOverAndStand.demo
    #behavioral_cloning:
      #strength: 0.5
      #demo_path: ../Demos/RollOverAndStand.demo
      #steps: 5000
      #samples_per_update: 0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 100
    summary_freq: 10000
    checkpoint_interval: 100000